### ISSUE TITLE
(ExUnit.TimeoutError) test timed out after 100ms.

### ISSUE THREAD

**Issue by kianmeng** [melpon/memoize#16]
Using the same version stated in `.tool-versions.

Running `test.sh` produces below error:

```
1) test doesn't block if caching process exited or crashed (Memoize.CacheTest)
     test/memoize_cache_test.exs:137
     ** (ExUnit.TimeoutError) test timed out after 100ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)
     
     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).
     
     code: assert 1 == Memoize.Cache.get_or_run(:key, fn -> 1 end)
     stacktrace:
       (elixir 1.11.0) lib/keyword.ex:218: Keyword.get/3
       (memoize 1.3.3) lib/memoize/cache.ex:179: Memoize.Cache.do_get_or_run/3
       test/memoize_cache_test.exs:145: (test)
       (ex_unit 1.11.0) lib/ex_unit/runner.ex:391: ExUnit.Runner.exec_test/1
       (stdlib 3.13.2) timer.erl:166: :timer.tc/1
       (ex_unit 1.11.0) lib/ex_unit/runner.ex:342: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

**Comment by melpon** [comment]
Fixed. Thank you for reporting!
