### ISSUE TITLE
Cannot run benchmark

### ISSUE THREAD

**Issue by kianmeng** [melpon/memoize#17]
Did I miss out anything?

```
$ cd bench
$ mix deps.get
** (CaseClauseError) no case clause matching: nil
    (stdlib 3.13.2) erl_eval.erl:968: :erl_eval.case_clauses/6
    (elixir 1.11.0) lib/code.ex:341: Code.eval_string_with_error_handling/3
    (elixir 1.11.0) lib/config.ex:252: Config.__eval__!/3
    (mix 1.11.0) lib/mix/tasks/loadconfig.ex:49: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.11.0) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.0) lib/mix/cli.ex:83: Mix.CLI.run_task/2
```

**Comment by melpon** [comment]
Benchmark is removed for outdated.
